# Generated by Django 4.2.1 on 2023-05-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_articles_cover_alter_articles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads'),
        ),
    ]
