# Generated by Django 4.2.1 on 2023-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_articles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='profile_photo',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(default='posts/default.png', upload_to='posts/'),
        ),
    ]
