# Generated by Django 4.2.1 on 2023-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_extenduser_profile_photo_alter_articles_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='description',
            field=models.CharField(default='', max_length=24),
        ),
    ]
