# Generated by Django 4.2.1 on 2023-05-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_extenduser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='description',
            field=models.CharField(default='', max_length=32),
        ),
    ]
