# Generated by Django 4.2.4 on 2023-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_articles_author_alter_articles_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(default='defaults/articles_default.png', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='profile_photo',
            field=models.ImageField(default='defaults/profile_default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Voluntário'), (2, 'Bolsista'), (3, 'Orientador'), (4, 'Administrador')], default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cover',
            field=models.ImageField(default='defaults/projects_default.png', upload_to='projects/'),
        ),
    ]
