# Generated by Django 4.2.4 on 2023-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_articles_cover_alter_extenduser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='description',
            field=models.CharField(blank=True, max_length=224),
        ),
    ]
